[package]
name = "obddimal"
version = "0.1.0"
edition = "2021"

[lib]
name = "obddimal"
path = "src/lib.rs"

[[bin]]
name = "obddimal"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# https://crates.io/crates/num-bigint
num-bigint = { version = "0.4" }

# https://crates.io/crates/num-traits
num-traits = { version = "0.2" }

regex = { version = "1.5" }

rustc-hash = { version = "1.0" }

rand = { version = "0.8.0" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bdd_creation"
harness = false
