[package]
name = "obddimal"
version = "0.1.0"
edition = "2021"

[profile.bench]
debug = true

[lib]
name = "obddimal"
path = "src/lib.rs"
bench = false

[[bin]]
name = "obddimal"
path = "src/main.rs"
bench = false

[[bench]]
name = "bdd_creation"
harness = false

[dependencies]
# https://crates.io/crates/num-bigint
num-bigint = { version = "0.4" }
# https://crates.io/crates/num-traits
num-traits = { version = "0.2" }
regex = { version = "1.5" }
rustc-hash = { version = "1.0" }
rand = { version = "0.8.0" }
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
