name: OBDDimal
version: "0.1"
about: A experimental, parallelized BDD library written in Rust.
author: Timo Netzer <timo.netzer@uni-ulm.de>

settings:
    - ArgRequiredElseHelp

args:
    - input:
        help: Input path to the CNF in DIMACS format (currently the only supported format).
        short: i
        long: input
        takes_value: true
    - load:
        help: Input path to a previously saved BDD.
        short: l
        long: load
        takes_value: true
    - preorder:
        help: Static variable ordering heuristic which is applied before the BDD is generated.
        short: p
        long: preorder
        possible_values:
            - FORCE
            - NONE
        takes_value: true
    - output:
        help: Serializes the BDD to the given path.
        short: o
        long: output
        takes_value: true
    - timer:
        help: Also prints how long the program was running before halting.
        short: t
        long: timer
    - verbose:
        help: Prints the selected options before running the program.
        short: v
        long: verbose